Repository 1bouillonbaptiste/athena, pull requests merged in 2024-09, with the labels that each got.

#31 :tada: Make `download` entrypoint callable
  athena/apicultor/client.py
  athena/apicultor/fetch.py
  athena/core/context.py
  athena/core/interfaces/__init__.py
  athena/core/interfaces/dataset_layout.py
  athena/core/interfaces/fluctuations.py
  athena/core/interfaces/layout.py
  athena/entrypoints/__init__.py
  athena/entrypoints/cli.py
  athena/entrypoints/download.py
  poetry.lock
  pyproject.toml
  tests/entrypoints/test_download.py
Labels: feature

#32 :tada: Convert fluctuations period
  athena/core/interfaces/fluctuations.py
  tests/conftest.py
  tests/entrypoints/test_download.py
  tests/types/interfaces/test_fluctuations_functions.py
  tests/types/interfaces/test_fluctuations_interface.py
Labels: feature

#34 :recycle: rename `apicultor` lib to `hub`
  athena/entrypoints/cli.py
  athena/hub/__init__.py
  athena/hub/client.py
  athena/hub/fetch.py
  tests/conftest.py
  tests/entrypoints/test_download.py
  tests/hub/test_client.py
  tests/hub/test_fetch.py
Labels: refacto

#35 :tada: download entrypoint update strategy
  README.md
  athena/entrypoints/cli.py
  athena/hub/fetch.py
Labels: feature

#37 :recycle: Fluctuations load and merge dynamically
  athena/core/interfaces/fluctuations.py
  tests/types/interfaces/test_fluctuations_functions.py
Labels: refacto

#38 :bug: fixed timezone bug in download entrypoint
  athena/core/interfaces/fluctuations.py
  athena/hub/client.py
  athena/hub/fetch.py
  tests/hub/test_fetch.py
Labels: bug

#40 :recycle: Rename optimize to tradingtools
  athena/optimize/__init__.py
  athena/tradingtools/__init__.py
  athena/tradingtools/backtesting.py
  athena/tradingtools/orders.py
  athena/tradingtools/strategies/__init__.py
  athena/tradingtools/strategies/dca.py
  athena/tradingtools/strategies/strategy.py
  tests/tradingtools/test_backtesting.py
  tests/tradingtools/test_orders.py
  tests/tradingtools/test_strategy.py
Labels: refacto

#41 :recycle: Merge Trade in Position
  athena/tradingtools/__init__.py
  athena/tradingtools/backtesting.py
  athena/tradingtools/orders.py
  tests/tradingtools/test_backtesting.py
  tests/tradingtools/test_orders.py
Labels: refacto

#45 :tada: sanitize candles list volume > 0
  athena/core/interfaces/fluctuations.py
  tests/types/interfaces/test_fluctuations_functions.py
Labels: feature

#49 :recycle: use default Coin values and various recycling
  athena/tradingtools/orders.py
  tests/tradingtools/test_backtesting.py
  tests/tradingtools/test_orders.py
  tests/tradingtools/test_performance_metrics.py
  tests/tradingtools/test_strategy.py
Labels: refacto

#48 :tada: First batch of trading metrics
  athena/core/types/enums.py
  athena/tradingtools/orders.py
  athena/tradingtools/performance_metrics.py
  tests/tradingtools/test_backtesting.py
  tests/tradingtools/test_orders.py
  tests/tradingtools/test_performance_metrics.py
  tests/tradingtools/test_strategy.py
Labels: feature

#50 :tada: Performance report
  athena/templates/performance_report.html
  athena/tradingtools/orders.py
  athena/tradingtools/performance_metrics.py
  athena/tradingtools/performance_report.py
  poetry.lock
  pyproject.toml
  tests/tradingtools/test_backtesting.py
  tests/tradingtools/test_performance_report.py
Labels: feature

#53 :tada: New backtest entrypoint
  README.md
  athena/core/context.py
  athena/entrypoints/cli.py
  athena/tradingtools/backtesting.py
  athena/tradingtools/strategies/__init__.py
  tests/entrypoints/test_backtest.py
Labels: feature

#54 :tada: Fluctuations from dataset
  athena/core/interfaces/fluctuations.py
  athena/hub/fetch.py
  athena/tradingtools/backtesting.py
  tests/conftest.py
  tests/entrypoints/test_backtest.py
  tests/entrypoints/test_download.py
  tests/types/interfaces/test_fluctuations_functions.py
  tests/types/interfaces/test_fluctuations_interface.py
Labels: feature

#55 :bug: Fluctuations period type
  athena/core/interfaces/fluctuations.py
  athena/core/types/period.py
  tests/types/interfaces/test_fluctuations_interface.py
Labels: refacto

#56 :recycle: Rename lib and move files
  athena/client/__init__.py
  athena/client/binance.py
  athena/client/fetch.py
  athena/entrypoints/cli.py
  tests/client/test_binance.py
  tests/client/test_fetch.py
  tests/conftest.py
  tests/core/interfaces/test_fluctuations_functions.py
  tests/core/interfaces/test_fluctuations_interface.py
  tests/core/types/test_period.py
  tests/entrypoints/test_download.py
Labels: refacto

#57 :recycle: Split CLI
  athena/cli.py
  athena/entrypoints/__init__.py
  athena/entrypoints/backtest.py
  athena/entrypoints/download.py
  poetry.lock
  pyproject.toml
  tests/entrypoints/test_backtest.py
  tests/entrypoints/test_download.py
Labels: refacto

#58 :recycle: Pydantic warnings
  athena/core/interfaces/fluctuations.py
Labels: bug

#59 :recycle: Sort all imports & minor changes
  .pre-commit-config.yaml
  athena/cli.py
  athena/client/binance.py
  athena/client/fetch.py
  athena/core/context.py
  athena/core/interfaces/__init__.py
  athena/core/interfaces/candle.py
  athena/core/interfaces/dataset_layout.py
  athena/core/interfaces/fluctuations.py
  athena/core/types/__init__.py
  athena/entrypoints/backtest.py
  athena/entrypoints/download.py
  athena/tradingtools/__init__.py
  athena/tradingtools/backtesting.py
  athena/tradingtools/orders.py
  athena/tradingtools/performance_report.py
  athena/tradingtools/strategies/strategy.py
  poetry.lock
  pyproject.toml
  tests/client/test_binance.py
  tests/client/test_fetch.py
  tests/conftest.py
  tests/core/interfaces/test_fluctuations_functions.py
  tests/core/interfaces/test_fluctuations_interface.py
  tests/entrypoints/test_backtest.py
  tests/entrypoints/test_download.py
  tests/tradingtools/test_backtesting.py
  tests/tradingtools/test_orders.py
  tests/tradingtools/test_performance_report.py
  tests/tradingtools/test_strategy.py
Labels: refacto

#60 :recycle: Backtest speed-up & fixes
  athena/core/interfaces/fluctuations.py
  athena/tradingtools/backtesting.py
  athena/tradingtools/performance_report.py
  tests/core/interfaces/test_fluctuations_functions.py
  tests/tradingtools/test_backtesting.py
  tests/tradingtools/test_performance_report.py
Labels: bug
